[project]
name = "planet"
version = "0.0.1"
description = "Clicker game."
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name = "Ben Kanter"},
  {name = "Adam Neeley"}
]

dependencies = [
  "pygame_ce",
  "pygame_gui",
  "toml",
  "pytest < 5.0.0",
  "pytest-cov[all]"
]

[project.urls]
repository = "https://github.com/wwafflless/PlanetClicker"

[tool.pytest.ini_options]
pythonpath = "."
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tools.pyright]
pythonpath = ["src"]
include = ["src"]
exclude = ["**/__pycache__"]
executionEnvironments = [
  { root = "." },
]

[project.scripts]
main = "main"
